import type { Showcase } from '@/domain/showcase';

export const seedShowcases: Showcase[] = [
  {
    id: 'showcase-build-with-ai-gallery',
    title: 'Build with AI Prototype Gallery',
    summary: 'Early prototype snapshots from GDGoC CNU Build with AI sessions.',
    body: 'Participants explored Gemini, Firebase, and AI-assisted coding tools to shape practical prototype ideas.',
    kind: 'gallery',
    imageUrl: '/showcases/build-with-ai-gallery.svg',
    tags: ['Build with AI', 'Gemini', 'Firebase'],
    visibility: 'public',
    status: 'published',
    publishedAt: '2026-05-11T09:00:00.000Z',
    createdAt: '2026-05-11T09:00:00.000Z',
    updatedAt: '2026-05-11T09:00:00.000Z',
  },
  {
    id: 'showcase-ai-sprint-retrospective',
    title: 'AI Sprint Retrospective',
    summary: 'What the chapter learned while turning AI ideas into demos.',
    kind: 'retrospective',
    tags: ['Retrospective', 'Vibe Coding'],
    visibility: 'member',
    status: 'published',
    publishedAt: '2026-05-10T09:00:00.000Z',
    createdAt: '2026-05-10T09:00:00.000Z',
    updatedAt: '2026-05-10T09:00:00.000Z',
  },
  {
    id: 'showcase-chapter-achievement',
    title: 'Chapter Build Milestone',
    summary: 'Operator-facing summary of prototype progress and follow-up work.',
    kind: 'achievement',
    tags: ['Achievement', 'Operations'],
    visibility: 'operator',
    status: 'published',
    publishedAt: '2026-05-09T09:00:00.000Z',
    createdAt: '2026-05-09T09:00:00.000Z',
    updatedAt: '2026-05-09T09:00:00.000Z',
  },
  {
    id: 'showcase-project-result-draft',
    title: 'Project Result Draft',
    summary: 'Draft project result reserved for operator editing.',
    kind: 'project_result',
    tags: ['Draft'],
    visibility: 'operator',
    status: 'draft',
    createdAt: '2026-05-08T09:00:00.000Z',
    updatedAt: '2026-05-08T09:00:00.000Z',
  },
];
